version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: burrow-server
    main: ./cmd/burrow-server
    binary: burrow-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - with_utls
      - with_quic
      - with_gvisor
      - with_wireguard
    ldflags:
      - -s -w
      - -X github.com/FrankFMY/burrow/internal/shared.Version={{.Version}}
      - -X github.com/FrankFMY/burrow/internal/shared.Commit={{.ShortCommit}}
      - -X github.com/FrankFMY/burrow/internal/shared.BuildDate={{.Date}}

  - id: burrow
    main: ./cmd/burrow
    binary: burrow
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    tags:
      - with_utls
      - with_quic
      - with_gvisor
      - with_wireguard
    ldflags:
      - -s -w
      - -X github.com/FrankFMY/burrow/internal/shared.Version={{.Version}}
      - -X github.com/FrankFMY/burrow/internal/shared.Commit={{.ShortCommit}}
      - -X github.com/FrankFMY/burrow/internal/shared.BuildDate={{.Date}}

archives:
  - id: burrow-server
    builds:
      - burrow-server
    name_template: "burrow-server_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

  - id: burrow
    builds:
      - burrow
    name_template: "burrow_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
